#!/bin/bash
# sentry-selfguard.sh - Dedicated self-protection monitor for Sentry scripts
# Watches the Sentry codebase itself for tampering.
# Any modification to Sentry scripts triggers:
#   1. Immediate structured log + alert
#   2. Integrity check (SHA-256 baseline comparison)
#   3. Optional enforcement (configurable severity)
#
# Design: runs alongside sandbox-monitor.fswatch.sh but with higher sensitivity
# and dedicated tamper-specific logging (selfguard.log).
#
# Usage:
#   sentry-selfguard.sh start        # Launch fswatch self-protection
#   sentry-selfguard.sh baseline     # Compute + store SHA-256 checksums
#   sentry-selfguard.sh verify       # One-shot integrity check
#   sentry-selfguard.sh status       # Show selfguard health

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SENTRY_HOME="${SENTRY_HOME:-$HOME/.hermes}"

# Load logger
if [[ -f "$SCRIPT_DIR/sentry-logger.sh" ]]; then
    source "$SCRIPT_DIR/sentry-logger.sh"
else
    echo "ERROR: sentry-logger.sh not found at $SCRIPT_DIR"
    exit 1
fi

# Load config
if [[ -f "$SCRIPT_DIR/sentry-config.sh" ]]; then
    source "$SCRIPT_DIR/sentry-config.sh"
    load_sentry_config 2>/dev/null || true
fi

# Self-guard specific paths
BASELINE_FILE="$SENTRY_HOME/sentry-baseline.sha256"
SELFGUARD_PID_FILE="$SENTRY_LOG_DIR/selfguard.pid"
ENFORCEMENT_SCRIPT="${ENFORCEMENT_SCRIPT:-$SCRIPT_DIR/enforcement_recovery_module.sh}"

# Files to protect (relative to SCRIPT_DIR)
PROTECTED_FILES=(
    "sentryctl"
    "sentry-config.sh"
    "sentry-logger.sh"
    "sentry-selfguard.sh"
    "sentry-status.sh"
    "sandbox-hooks.zsh"
    "sandbox-monitor.fswatch.sh"
    "enforcement_recovery_module.sh"
    "sandbox-egress-watcher.sh"
)

PROTECTED_DIRS=(
    "$SCRIPT_DIR"
    "$SENTRY_HOME"
)

# --- Baseline management ---

compute_baseline() {
    echo "Computing SHA-256 baseline for Sentry scripts..."
    local tmp
    tmp=$(mktemp)

    echo "# Sentry integrity baseline - $(date -Iseconds)" > "$tmp"
    echo "# Auto-generated by sentry-selfguard.sh" >> "$tmp"
    echo "" >> "$tmp"

    local count=0
    for f in "${PROTECTED_FILES[@]}"; do
        local full_path="$SCRIPT_DIR/$f"
        if [[ -f "$full_path" ]]; then
            local hash
            if command -v shasum >/dev/null 2>&1; then
                hash=$(shasum -a 256 "$full_path" | awk '{print $1}')
            else
                hash=$(sha256sum "$full_path" | awk '{print $1}')
            fi
            echo "$hash  $f" >> "$tmp"
            ((count++))
        fi
    done

    # Also hash the safety rules and config
    for f in "$SENTRY_HOME/sentry-config.json" "$SENTRY_HOME/safety-rules.json"; do
        if [[ -f "$f" ]]; then
            local hash
            if command -v shasum >/dev/null 2>&1; then
                hash=$(shasum -a 256 "$f" | awk '{print $1}')
            else
                hash=$(sha256sum "$f" | awk '{print $1}')
            fi
            echo "$hash  $(basename "$f")" >> "$tmp"
            ((count++))
        fi
    done

    mv "$tmp" "$BASELINE_FILE"
    chmod 600 "$BASELINE_FILE" 2>/dev/null || true

    echo "Baseline saved: $BASELINE_FILE ($count files hashed)"
    log_selfguard "BASELINE" "Computed integrity baseline for $count protected files" \
        "{\"count\":$count,\"baseline_file\":\"$BASELINE_FILE\"}"
}

verify_integrity() {
    if [[ ! -f "$BASELINE_FILE" ]]; then
        echo "No baseline found. Run: $0 baseline"
        return 1
    fi

    local tampered=0
    local checked=0
    local results=()

    while IFS= read -r line; do
        # Skip comments and empty lines
        [[ "$line" =~ ^#.*$ || -z "$line" ]] && continue

        local expected_hash file_ref
        expected_hash=$(echo "$line" | awk '{print $1}')
        file_ref=$(echo "$line" | awk '{print $2}')

        # Resolve file path
        local full_path
        case "$file_ref" in
            sentry-config.json|safety-rules.json)
                full_path="$SENTRY_HOME/$file_ref" ;;
            *)
                full_path="$SCRIPT_DIR/$file_ref" ;;
        esac

        if [[ ! -f "$full_path" ]]; then
            results+=("MISSING: $file_ref")
            ((tampered++))
            ((checked++))
            continue
        fi

        local actual_hash
        if command -v shasum >/dev/null 2>&1; then
            actual_hash=$(shasum -a 256 "$full_path" | awk '{print $1}')
        else
            actual_hash=$(sha256sum "$full_path" | awk '{print $1}')
        fi

        if [[ "$actual_hash" != "$expected_hash" ]]; then
            results+=("TAMPERED: $file_ref (expected ${expected_hash:0:12}... got ${actual_hash:0:12}...)")
            ((tampered++))
        else
            results+=("OK: $file_ref")
        fi
        ((checked++))
    done < "$BASELINE_FILE"

    echo "=== Sentry Integrity Check ==="
    echo "Checked: $checked files"
    echo "Tampered/Missing: $tampered"
    echo ""
    for r in "${results[@]}"; do
        if [[ "$r" == TAMPERED* || "$r" == MISSING* ]]; then
            echo "  🔴 $r"
        else
            echo "  🟢 $r"
        fi
    done

    if (( tampered > 0 )); then
        log_selfguard "INTEGRITY_FAIL" "$tampered file(s) failed integrity check" \
            "{\"tampered\":$tampered,\"checked\":$checked}"
        return 1
    else
        log_selfguard "INTEGRITY_OK" "All $checked files passed integrity check" \
            "{\"checked\":$checked}"
        return 0
    fi
}

# --- fswatch self-protection monitor ---

start_selfguard() {
    if ! command -v fswatch >/dev/null 2>&1; then
        echo "ERROR: fswatch not installed. Install with: brew install fswatch"
        exit 1
    fi

    # Compute baseline if not exists
    if [[ ! -f "$BASELINE_FILE" ]]; then
        compute_baseline
    fi

    echo "=== Sentry Selfguard Monitor ==="
    echo "Watching: ${PROTECTED_DIRS[*]}"
    echo "Baseline: $BASELINE_FILE"
    echo "Any modification to Sentry scripts triggers tamper alert."
    echo "PID: $$"
    echo ""

    # Store PID for status checks
    echo "$$" > "$SELFGUARD_PID_FILE"

    # Cleanup on exit
    trap 'rm -f "$SELFGUARD_PID_FILE"; echo "Selfguard stopped."' EXIT

    # Start fswatch on protected dirs
    fswatch -r -x --event-flags "${PROTECTED_DIRS[@]}" 2>/dev/null | while IFS= read -r line; do
        # Parse the event
        local path events
        local event_regex=' (Removed|Renamed|Updated|Attribute Modified|PlatformSpecific|Created|Moved|IsDir|IsFile)'
        if [[ "$line" =~ $event_regex ]]; then
            path="${line%%$event_regex*}"
            events="${line#*${path} }"
        else
            path="$line"
            events="Unknown"
        fi

        # Filter: only care about modifications to Sentry-related files
        local is_sentry_file=false
        local matched_file=""

        for f in "${PROTECTED_FILES[@]}"; do
            if [[ "$path" == *"$f" ]]; then
                is_sentry_file=true
                matched_file="$f"
                break
            fi
        done

        # Also check config files
        if [[ "$path" == *"sentry-config.json" || "$path" == *"safety-rules.json" ]]; then
            is_sentry_file=true
            matched_file=$(basename "$path")
        fi

        # Skip our own log writes
        if [[ "$path" == *".log" || "$path" == *".pid" || "$path" == *".rotate_counter" ]]; then
            continue
        fi

        if $is_sentry_file; then
            local reason="TAMPER: Sentry file '$matched_file' was modified ($events)"
            echo "🚨 [SELFGUARD] $reason"
            echo "   Path: $path"
            echo "   Events: $events"
            echo "   Time: $(date)"

            # Structured log
            log_selfguard "TAMPER" "$reason" \
                "{\"file\":\"$matched_file\",\"path\":\"$path\",\"events\":\"$events\"}"

            # macOS notification
            osascript -e "display notification \"Sentry file '$matched_file' was modified! Check integrity.\" with title \"🚨 SENTRY TAMPER ALERT\"" 2>/dev/null || true

            # Run integrity check
            echo ""
            echo "Running integrity verification..."
            verify_integrity || true

            # Trigger enforcement if in hard mode
            if [[ "${SENTRY_MODE:-soft-block}" == "hard" ]]; then
                echo "Hard mode: triggering enforcement for tamper event..."
                if [[ -x "$ENFORCEMENT_SCRIPT" ]]; then
                    "$ENFORCEMENT_SCRIPT" enforce "SELFGUARD TAMPER: $matched_file modified" || true
                fi
            fi

            # Also update baseline after legitimate edits (user can re-run baseline manually)
            echo ""
            echo "If this was a legitimate edit, re-run: $0 baseline"
        fi
    done
}

# --- Status ---

selfguard_status() {
    echo "=== Sentry Selfguard Status ==="
    echo ""

    # Check if running
    if [[ -f "$SELFGUARD_PID_FILE" ]]; then
        local pid
        pid=$(cat "$SELFGUARD_PID_FILE" 2>/dev/null || echo "")
        if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
            echo "Selfguard monitor: RUNNING (PID $pid)"
        else
            echo "Selfguard monitor: STALE PID FILE (PID $pid not running)"
        fi
    else
        echo "Selfguard monitor: NOT RUNNING"
    fi

    echo ""

    # Baseline status
    if [[ -f "$BASELINE_FILE" ]]; then
        local age
        age=$(stat -f "%Sm" -t "%Y-%m-%d %H:%M" "$BASELINE_FILE" 2>/dev/null || \
              stat -c "%y" "$BASELINE_FILE" 2>/dev/null | cut -d. -f1 || echo "unknown")
        local count
        count=$(grep -v '^#' "$BASELINE_FILE" | grep -v '^$' | wc -l | tr -d ' ')
        echo "Baseline file: $BASELINE_FILE"
        echo "  Last updated: $age"
        echo "  Files tracked: $count"
    else
        echo "Baseline file: NOT CREATED (run: $0 baseline)"
    fi

    echo ""

    # Selfguard log
    if [[ -f "$SENTRY_SELFLOG" ]]; then
        local total
        total=$(wc -l < "$SENTRY_SELFLOG" 2>/dev/null | tr -d ' ')
        local tamper_count
        tamper_count=$(grep -c '"TAMPER"' "$SENTRY_SELFLOG" 2>/dev/null) || tamper_count=0
        echo "Selfguard log: $SENTRY_SELFLOG"
        echo "  Total events: $total"
        echo "  Tamper events: $tamper_count"

        if (( total > 0 )); then
            echo ""
            echo "  Last 3 events:"
            tail -3 "$SENTRY_SELFLOG" | while read -r line; do
                if command -v jq >/dev/null 2>&1; then
                    local ts decision reason
                    ts=$(echo "$line" | jq -r '.ts // ""' | cut -d'T' -f2 | cut -d'+' -f1)
                    decision=$(echo "$line" | jq -r '.decision // ""')
                    reason=$(echo "$line" | jq -r '.reason // ""' | cut -c1-70)
                    printf "    [%s] %s - %s\n" "$ts" "$decision" "$reason"
                else
                    echo "    $line"
                fi
            done
        fi
    else
        echo "Selfguard log: no events yet"
    fi
}

# --- Main ---

case "${1:-status}" in
    start|monitor)
        start_selfguard
        ;;
    baseline|hash)
        compute_baseline
        ;;
    verify|check)
        verify_integrity
        ;;
    status)
        selfguard_status
        ;;
    *)
        echo "Usage: $0 {start|baseline|verify|status}"
        echo ""
        echo "  start     - Launch fswatch self-protection monitor"
        echo "  baseline  - Compute SHA-256 checksums of protected files"
        echo "  verify    - One-shot integrity check against baseline"
        echo "  status    - Show selfguard health and recent events"
        exit 1
        ;;
esac
